# -*- coding: utf-8 -*-
"""Titanic Data Cleaning & Preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Orp3di8LCLCUztCyvUE_s-9P4Na9FLii
"""

import pandas as pd
import numpy as np
from google.colab import files

print("Please upload Titanic dataset (CSV file)")
uploaded = files.upload()
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)
print("\n🔹 Original Dataset Preview:")
print(df.head())
print("\n Dataset Info:")
print(df.info())
print("\n Missing Values Before Cleaning:")
print(df.isnull().sum())
if 'Age' in df.columns:
    df['Age'].fillna(df['Age'].mean(), inplace=True)
if 'Embarked' in df.columns:
    df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
if 'Cabin' in df.columns:
    df.drop('Cabin', axis=1, inplace=True)

print("\ Missing values handled")
duplicates = df.duplicated().sum()
print(f"\n Duplicate Rows Before: {duplicates}")
df.drop_duplicates(inplace=True)

print(" Duplicates removed")
if 'Survived' in df.columns:
    df['Survived'] = df['Survived'].astype('category')
if 'Sex' in df.columns:
    df['Sex'] = df['Sex'].astype('category')
print("\n Data Types After Conversion:")
print(df.dtypes)
df.columns = df.columns.str.lower()
print("\nRenamed Columns:")
print(df.columns)
print("\n Cleaned Dataset Preview:")
print(df.head())
df.to_csv("clean_titanic.csv", index=False)
print("\nClean dataset saved as 'clean_titanic.csv'")
files.download("clean_titanic.csv")

